"use client"
import Toast from '@/components/toast/Toast'
import './globals.css'
import { useEffect, useState } from 'react'
import logo from '../public/assets/others/load.gif'
import Image from 'next/image'
import { Provider } from 'react-redux'
import { store } from '@/redux/store/store'



// export const metadata = {
//   title: 'Inventory Management Software',
//   description: 'Generated by create next app',
// }



export default function RootLayout({ children }) {
  const [loadding, setLoadding] = useState(true);


  useEffect(() => {
    setTimeout(() => {
      setLoadding(false);
    }, 1000);
  })



  return (
    <html lang="en">
      <title>Inventory Management Software</title>
      <body>
        {/* {
          loadding ?
            <div className="loadding-image grid place-content-center  mt-24">
              <Image src={logo} alt='loading' height={500} width={500} className='object-cover' />
            </div>
            :
            <>
              {children}
              < Toast />
            </>
        } */}
        <Provider store={store}>
          {children}
          < Toast />
        </Provider>

      </body>
    </html>
  )
}
