"use client"
import Toast from '@/components/toast/Toast'
import './globals.css'
import { useEffect, useState } from 'react'



// export const metadata = {
//   title: 'Inventory Management Software',
//   description: 'Generated by create next app',
// }



export default function RootLayout({ children }) {
  const [loadding, setLoadding] = useState(true);


  useEffect(() => {
    setTimeout(() => {
      setLoadding(false);
    }, 1000);
  })



  return (
    <html lang="en">
      <title>Inventory Management Software</title>
      <body>
        {children}
        <Toast />
      </body>
    </html>
  )
}
